#!/bin/sh

TAIL="$(which tail)"
GREP="$(which grep)"
CAT="$(which cat)"
SED="$(which sed)"

$CAT ~/.ssh/config | $GREP -B 1 "^Host" | $TAIL -rn100000 | $GREP -B 1 --color=always -i "${1}" | \
    $SED -e $'s/Host/------------------------------------------------------------\\\n/g' | \
    $SED -e $'s/#/------------------------------------------------------------\\\n/g'

