#!/bin/sh

if [ -z "${1}" ]; then
	echo "enter a search string"
	exit 1
fi

TAIL="$(which tail)"
GREP="$(which grep)"
CAT="$(which cat)"
SED="$(which sed)"
ACK="$(which ack)"

$CAT ~/.ssh/config | $SED -n "/^# @vhosts.*${1}/,/^Host/p" | $TAIL -rn100000 \
	| $SED '/^Host\s/i\\n============================================================' \
	| $SED '/^Host\s/a============================================================' \
	| $ACK --passthru "${1}"

